cloudflared:
  credentials:
    existingSecret: cloudflared-credentials
  config:
    tunnel: homelab
    ingress:
      # It is safe to put a wildcard here
      # Please see https://homelab.example.com/reference/faq.html#is-it-safe-to-use-wildcard-in-cloudflare-tunnel-ingress-config
      - hostname: '*.example.com'
        service: https://ingress-nginx-controller.ingress-nginx
        originRequest:
          noTLSVerify: true
      - service: http_status:404

  podMonitor:
    enabled: true
    metricsEndpoints:
      - port: http
